<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="DROP_SCREW" Id="{79fa5298-4375-4dd8-8def-d4665220c462}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK DROP_SCREW
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="DROP_SCREW">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>