<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="PICKUP_SCREW" Id="{99d35285-e01c-443f-8d46-44984eaa44c8}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK PICKUP_SCREW
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="PICKUP_SCREW">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>