<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="POSITION_RUN" Id="{c551cb44-1c9b-4b52-a57d-c2b3ff4bdadb}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK POSITION_RUN
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="POSITION_RUN">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>