<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="FEEDERS_HOME_SEQ" Id="{2da5084c-3ab1-48e0-8554-c9237a62e0bd}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FEEDERS_HOME_SEQ
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FEEDERS_HOME_SEQ">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>