<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="SELECT_ACTIVE_FEEDER_SEQ" Id="{c85cf2b2-f7f2-4ead-a0b3-57d755304991}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK SELECT_ACTIVE_FEEDER_SEQ
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="SELECT_ACTIVE_FEEDER_SEQ">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>