<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="AUTOMATIC_SCREW_PICKUP_TEST" Id="{4cb08561-5be3-47cc-b299-483650213744}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK AUTOMATIC_SCREW_PICKUP_TEST
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="AUTOMATIC_SCREW_PICKUP_TEST">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>