<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="AUTOMATIC_SCREWING" Id="{4784e865-14ee-4869-804b-679825818e9e}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK AUTOMATIC_SCREWING
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="AUTOMATIC_SCREWING">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>