<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="FAST" Id="{346f77cf-e7e3-4cc8-8cea-585644fa2845}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM FAST
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FAST">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>