<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="INDEP" Id="{14ae7ba1-7509-475f-af40-69a58bd85d3b}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM INDEP
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="INDEP">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>