<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="JIG" Id="{17448e34-6352-4909-9200-b00c8ac4245a}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM JIG
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="JIG">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>