<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="AUTO_SCREWPICKUP" Id="{c4db5fdc-7d52-49e3-beb9-79bd9a3b7f44}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM AUTO_SCREWPICKUP
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="AUTO_SCREWPICKUP">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>