<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="AUTO_POSITION" Id="{cdfbe012-5152-443d-959b-b56c2dafcd18}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM AUTO_POSITION
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="AUTO_POSITION">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>