<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="AUTO_SCREWLENGTH" Id="{0204b2d1-fbb4-4780-b187-5cd2aeb8d721}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM AUTO_SCREWLENGTH
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="AUTO_SCREWLENGTH">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>