<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="CreateRecipeFile" Id="{21b267a5-cfef-492a-83c2-e2e2b8265fee}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK CreateRecipeFile
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="CreateRecipeFile">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>