<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="ReadRecipeFromFile" Id="{f2ca5823-87be-4e5b-a7f8-ec8da86c7b10}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK ReadRecipeFromFile
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="ReadRecipeFromFile">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>