<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="WriteRepcieToFile" Id="{ce6b6279-2310-40ab-93f7-1b8aa4dc5c24}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK WriteRepcieToFile
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="WriteRepcieToFile">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>