<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="JIG_TAKER" Id="{56c7505f-2c83-448f-9292-c4eafd49cefb}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM JIG_TAKER
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="JIG_TAKER">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>