<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="JIG_GRAB" Id="{0b02a691-20a2-49ff-85ea-fb6d489239c2}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM JIG_GRAB
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="JIG_GRAB">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>