<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="ConvertCommandToString" Id="{2416dfc4-341c-4a9a-aa16-3e8ed03ee0bd}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK ConvertCommandToString
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="ConvertCommandToString">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>