<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="JIG002_MANSCANIA2016" Id="{ff368a16-e9de-463e-b220-2133544492e6}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM JIG002_MANSCANIA2016
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="JIG002_MANSCANIA2016">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>