<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="JIG005_BMW_MGU" Id="{f2c4ef82-5da5-4c7c-bcdd-a2559f874752}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM JIG005_BMW_MGU
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="JIG005_BMW_MGU">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>