<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="AST40_Controller" Id="{1db48b83-1c1e-4170-aa6c-e6f8192c6e0f}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM AST40_Controller
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="AST40_Controller">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>