<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="HMI_Controller" Id="{521f5e38-1cb7-446b-8876-1aa8d0f3da0a}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM HMI_Controller
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="HMI_Controller">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>