<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="HOME_Sequence" Id="{b03a89ed-2621-4266-b115-c87329874470}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM HOME_Sequence
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="HOME_Sequence">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>