<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="MES_Controller" Id="{68dc098d-b5d8-4165-929f-a366b3e946c8}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MES_Controller
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[IF G_xComProtocol THEN
	OPCUA_Controller();
ELSE
	LOCAL_COM_Controller();
END_IF]]></ST>
    </Implementation>
    <LineIds Name="MES_Controller">
      <LineId Id="5" Count="0" />
      <LineId Id="8" Count="0" />
      <LineId Id="6" Count="0" />
      <LineId Id="9" Count="0" />
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>