<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="RECIPE_Controller" Id="{fe0b8a2c-7755-48b6-8b7f-aa457ab7aa7b}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM RECIPE_Controller
VAR	
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="RECIPE_Controller">
      <LineId Id="12" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>